#!/usr/bin/env sh

dbus-update-activation-environment DISPLAY XAUTHORITY
systemctl --user import-environment DISPLAY XAUTHORITY

export XDG_CURRENT_DSEKTOP=spectrwm
export XDG_SESSION_DESKTOP=spectrwm

dunst &
nvidia-settings --config="$XDG_CONFIG_HOME/nvidia/settings" --load-config-only &
openrgb -p default &
picom &
redshift -PO 6000  &
wallpaper &
xss-lock lockscreen &

while true; do
    xprop -root -set WM_NAME " $(date +"%F %T") "
    sleep 1
done &

exec spectrwm
