#!/usr/bin/env sh

# Xresources settings
xrdb -merge "$HOME/.config/xorg/xresources"

# Scripts related to xinit
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
done

# The desktop
DESKTOP="spectrwm"

# Desktop export variables
export DESKTOP_SESSION="$DESKTOP"
export XDG_CURRENT_DSEKTOP="$DESKTOP"
export XDG_SESSION_DESKTOP="$DESKTOP"
export XDG_SESSION_TYPE="x11"

# Autostart
dunst &
echo 15 | canvas -B -a &
nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings --load-config-only &
openrgb -p default &
picom &
redshift -PO 6000 &
setxkbmap -layout us -variant colemak &
xbanish &
xset r 66 &
xset r rate 300 30 &
xset s off -dpms &
xsetroot -cursor_name left_ptr &

# Execute the window manager
exec "$DESKTOP"
