#!/usr/bin/env sh

# Scripts related to xinit
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
done

# Desktop export variables
desktop="spectrwm"
export XDG_CURRENT_DSEKTOP="$DESKTOP"
export XDG_SESSION_DESKTOP="$DESKTOP"

# Autostart
"$HOME/.fehbg" &
openrgb -p default &
redshift -PO 6000 &
setxkbmap -layout us -variant colemak &
xautolock -time 5 -locker i3lock-conf &
xbanish -i all &
xset r 66 &
xset r rate 300 30 &

# Execute the window manager
exec "$DESKTOP"
