#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# Settings
bspc monitor DVI-D-0 -d main web
bspc monitor HDMI-0 -d term chat hide
bspc config border_width 2
bspc config window_gap 9
bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#bd93f9"
bspc config urgent "#ff5555"
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zoom floating=on
