#!/usr/bin/env sh

rm /tmp/fzfmenu

"$@" sh -c 'FZF_DEFAULT_OPTS="--layout=reverse --no-separator --no-scrollbar --color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4" IFS=":"; for p in $PATH; do find "$p" -type f -executable 2> /dev/null; done | sort -u | fzf > /tmp/fzfmenu'

exec $(cat /tmp/fzfmenu)
