abbr -a --position anywhere c "$PAGER"
abbr -a --position anywhere co "cargo"
abbr -a --position anywhere connect "iwctl station wlan0 connect Atheer"
abbr -a --position anywhere cp "cp -iv"
abbr -a --position anywhere crypto "curl -sL rate.sx/"
abbr -a --position anywhere ctl "systemctl"
abbr -a --position anywhere dad "curl -sL icanhazdadjoke.com/"
abbr -a --position anywhere disconnect "iwctl station wlan0 disconnect"
abbr -a --position anywhere g "git"
abbr -a --position anywhere gignore "curl -sL gitignore.io/api/"
abbr -a --position anywhere ip "ip -c=auto"
abbr -a --position anywhere ka "killall"
abbr -a --position anywhere l "exa --git -Fas=Name --group-directories-first"
abbr -a --position anywhere ll "exa --git -Flas=Name --group-directories-first"
abbr -a --position anywhere m "batman"
abbr -a --position anywhere mk "make"
abbr -a --position anywhere mkd "mkdir -pv"
abbr -a --position anywhere mv "mv -iv"
abbr -a --position anywhere p "paru"
abbr -a --position anywhere parrot "curl -sL parrot.live"
abbr -a --position anywhere pkgclean "paru -c && paru -Sc && paccache -r"
abbr -a --position anywhere pp "prettyping"
abbr -a --position anywhere pubip "curl -sL ifconfig.co/"
abbr -a --position anywhere r "rm -vI"
abbr -a --position anywhere s "$(command -v doas &> /dev/null && echo doas || echo sudo)"
abbr -a --position anywhere sx "startx"
abbr -a --position anywhere tp "btop"
abbr -a --position anywhere v "$EDITOR"
abbr -a --position anywhere wttr "curl -sL wttr.in/"
