# Abbreviations that I use
abbr -a c "$PAGER"
abbr -a co "cargo"
abbr -a connect "iwctl station wlan0 connect Atheer"
abbr -a cp "cp -iv"
abbr -a crypto "curl -sL rate.sx/"
abbr -a ctl "systemctl"
abbr -a dad "curl -sL icanhazdadjoke.com/"
abbr -a disconnect "iwctl station wlan0 disconnect"
abbr -a g "git"
abbr -a gignore "curl -sL gitignore.io/api/"
abbr -a ip "ip -c=auto"
abbr -a ka "killall"
abbr -a l "exa --git -Fas=Name --group-directories-first"
abbr -a ll "exa --git -Flas=Name --group-directories-first"
abbr -a m "batman"
abbr -a mk "colormake"
abbr -a mkd "mkdir -pv"
abbr -a mv "mv -iv"
abbr -a p "paru"
abbr -a parrot "curl -sL parrot.live"
abbr -a pkgclean "paru -c && paru -Sc && paccache -r"
abbr -a pm "pulsemixer"
abbr -a pp "prettyping"
abbr -a pubip "curl -sL ifconfig.co/"
abbr -a r "rm -vI"
abbr -a s "$(command -v doas &> /dev/null && echo doas || echo sudo)"
abbr -a sx "startx"
abbr -a tp "btop"
abbr -a v "$EDITOR"
abbr -a wttr "curl -sL wttr.in/"
