function fish_prompt -d "Write out the prompt"
    set_color -o "magenta"
    printf "["
    set_color -o "green"
    printf "$USER"
    set_color -o "magenta"
    printf "@"
    set_color -o "yellow"
    printf "$(prompt_pwd)"
    set_color -o "magenta"
    printf "] "
    set_color -o "red"
    printf "$status"
    set_color -o "cyan"
    printf "$(fish_is_root_user && printf \# || printf \$) "
    set_color "normal"
end
