#!/bin/sh
userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps
if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Autostart
$HOME/.config/polybar/launch.sh &
/usr/lib/geoclue-2.0/demos/agent &
dunst &
echo 10 | canvas -S 1920x1080 -B -n -a &
picom --experimental-backends &
setxkbmap -layout us -variant colemak &
xautolock -time 5 -locker i3lock-conf &
xbanish &
xset r 66 &
xset r rate 300 40 &
xsetroot -cursor_name left_ptr &

# Start window manager
exec leftwm
