#!/usr/bin/env sh

exec yt-dlp --embed-thumbnail --download-archive download-archive.txt --no-post-overwrites -iwx --audio-format opus -o "%(channel)s - %(title)s [%(id)s].%(ext)s" "https://www.youtube.com/playlist?list=PLycMymTUi1MAVImVNyHThM0aKvbtDxwCc"
