# Variables
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export CARGO_HOME="$XDG_DATA_HOME/cargo"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export GOPATH="$XDG_DATA_HOME/go"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export HISTFILE="$XDG_STATE_HOME/bash/history"

if [[ $(which bat) != "" ]]; then
	export PAGER="bat -p"
fi
export BAT_THEME="Dracula"
export CC="clang"
export CXX="clang++"
if [[ $(which nvim) != "" ]]; then
	export EDITOR="nvim"
fi
if [[ $(which ninja) != "" ]]; then
	export CMAKE_GENERATOR="Ninja"
fi
export PF_INFO="ascii title host kernel os shell uptime memory wm palette"
export EXA_COLORS="da=35"

export PATH="${PATH:+${PATH}:}$HOME/.local/bin:$CARGO_HOME/bin:$GOPATH/bin"

source ~/.bashrc
